# Generated by Django 2.2.10 on 2022-01-10 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'reply by text'), (2, 'reply by choice'), (3, 'reply by multiple choices')], verbose_name='type')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questioning.Question', verbose_name='question')),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='responder unique id')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 1, 10, 20, 29, 27, 308787, tzinfo=utc), verbose_name='created date time')),
                ('title', models.CharField(max_length=200, verbose_name='survey title')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 1, 10, 20, 29, 27, 308732, tzinfo=utc), verbose_name='start date time')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 1, 20, 20, 29, 27, 308759, tzinfo=utc), verbose_name='end date time')),
                ('description', models.TextField(verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('responders', models.ManyToManyField(to='questioning.Responder', verbose_name='responders')),
            ],
        ),
        migrations.CreateModel(
            name='ResponderAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questioning.QuestionAnswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questioning.Question')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questioning.Responder')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questioning.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='responder',
            name='responded_surveys',
            field=models.ManyToManyField(to='questioning.Survey', verbose_name='responded surveys'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questioning.Survey', verbose_name='survey'),
        ),
    ]
