# Generated by Django 4.0.1 on 2022-01-11 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0002_auto_20220111_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='create_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 1, 11, 9, 6, 50, 716987, tzinfo=utc), verbose_name='created date time'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 9, 6, 50, 716958, tzinfo=utc), verbose_name='end date time'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 9, 6, 50, 716929, tzinfo=utc), verbose_name='start date time'),
        ),
    ]
